version: '3'
services:
  db:
    image: mariadb:10.2
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bezbednost
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - bezbednostnet
volumes:
  mysqldata:
networks:
  bezbednostnet: